apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hpc
  labels:
    app: hpc
spec:
  selector:
    matchLabels:
      app: hpc
  template:
    metadata:
      labels:
        app: hpc
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: hpc
          image: containerrollingregistry.azurecr.io/hpcagent:v16.0
          securityContext:
            windowsOptions:
              hostProcess: true
              runAsUserName: "NT AUTHORITY\\SYSTEM"
          command: ["powershell", "-c", "c:/hpc/startMonagent.ps1 /subscriptions/1c8c4edc-b188-4199-9580-3173033d75f7/resourcegroups/containerRolling/providers/Microsoft.ManagedIdentity/userAssignedIdentities/containerRollingMI 1c8c4edc-b188-4199-9580-3173033d75f7 containerrolling-capz containerrolling-capz 1.20"]
          imagePullPolicy: IfNotPresent
      hostNetwork: true
      terminationGracePeriodSeconds: 0
